// type: "word" = 英単語, "idiom" = 熟語
const WORDS = [
  // ---- 英単語 ----
  { type: "word", en: "achieve", ja: "達成する", ex: "She worked hard to achieve her goal." },
  { type: "word", en: "adapt", ja: "適応する", ex: "Animals adapt to their environment." },
  { type: "word", en: "advantage", ja: "利点", ex: "Speaking English is a big advantage." },
  { type: "word", en: "ancient", ja: "古代の", ex: "We visited an ancient temple." },
  { type: "word", en: "appreciate", ja: "感謝する", ex: "I really appreciate your help." },
  { type: "word", en: "attempt", ja: "試みる", ex: "He attempted to climb the mountain." },
  { type: "word", en: "avoid", ja: "避ける", ex: "You should avoid eating too much sugar." },
  { type: "word", en: "benefit", ja: "利益", ex: "Exercise has many health benefits." },
  { type: "word", en: "borrow", ja: "借りる", ex: "Can I borrow your pen?" },
  { type: "word", en: "century", ja: "世紀", ex: "This house was built a century ago." },
  { type: "word", en: "challenge", ja: "挑戦", ex: "Learning a language is a challenge." },
  { type: "word", en: "communicate", ja: "意思疎通する", ex: "We communicate by email." },
  { type: "word", en: "compare", ja: "比較する", ex: "Don't compare yourself with others." },
  { type: "word", en: "confident", ja: "自信のある", ex: "She is confident about the test." },
  { type: "word", en: "consider", ja: "よく考える", ex: "Please consider my offer." },
  { type: "word", en: "create", ja: "創造する", ex: "Artists create beautiful things." },
  { type: "word", en: "decide", ja: "決める", ex: "I decided to study abroad." },
  { type: "word", en: "delicious", ja: "とてもおいしい", ex: "This cake is delicious." },
  { type: "word", en: "describe", ja: "説明する", ex: "Can you describe the man you saw?" },
  { type: "word", en: "discover", ja: "発見する", ex: "Scientists discovered a new planet." },
  { type: "word", en: "enough", ja: "十分な", ex: "Do we have enough time?" },
  { type: "word", en: "environment", ja: "環境", ex: "We must protect the environment." },
  { type: "word", en: "experience", ja: "経験", ex: "He has a lot of teaching experience." },
  { type: "word", en: "familiar", ja: "よく知っている", ex: "That song sounds familiar." },
  { type: "word", en: "foreign", ja: "外国の", ex: "She speaks three foreign languages." },
  { type: "word", en: "generous", ja: "気前のよい", ex: "He is generous to everyone." },
  { type: "word", en: "honest", ja: "正直な", ex: "An honest answer is best." },
  { type: "word", en: "imagine", ja: "想像する", ex: "Imagine you are on a beach." },
  { type: "word", en: "improve", ja: "上達させる", ex: "I want to improve my English." },
  { type: "word", en: "necessary", ja: "必要な", ex: "Is it necessary to go today?" },
  { type: "word", en: "opportunity", ja: "機会", ex: "This is a great opportunity." },
  { type: "word", en: "prepare", ja: "準備する", ex: "I need to prepare for the exam." },
  { type: "word", en: "receive", ja: "受け取る", ex: "I received a letter yesterday." },
  { type: "word", en: "recommend", ja: "勧める", ex: "I recommend this restaurant." },
  { type: "word", en: "reduce", ja: "減らす", ex: "We should reduce waste." },
  { type: "word", en: "responsible", ja: "責任のある", ex: "He is responsible for the project." },
  { type: "word", en: "separate", ja: "分ける", ex: "Please separate the trash." },
  { type: "word", en: "succeed", ja: "成功する", ex: "You will succeed if you try." },
  { type: "word", en: "suggest", ja: "提案する", ex: "I suggest taking a break." },
  { type: "word", en: "tradition", ja: "伝統", ex: "It is a Japanese tradition." },
  { type: "word", en: "valuable", ja: "貴重な", ex: "Time is valuable." },
  // ---- 熟語 ----
  { type: "idiom", en: "look forward to ~", ja: "~を楽しみに待つ", ex: "I look forward to seeing you." },
  { type: "idiom", en: "give up", ja: "あきらめる", ex: "Never give up on your dreams." },
  { type: "idiom", en: "take care of ~", ja: "~の世話をする", ex: "She takes care of her little brother." },
  { type: "idiom", en: "find out", ja: "見つけ出す、知る", ex: "I found out the truth." },
  { type: "idiom", en: "get along with ~", ja: "~と仲良くやる", ex: "I get along with my classmates." },
  { type: "idiom", en: "put off", ja: "延期する", ex: "Don't put off your homework." },
  { type: "idiom", en: "come up with ~", ja: "~を思いつく", ex: "He came up with a good idea." },
  { type: "idiom", en: "run out of ~", ja: "~を使い果たす", ex: "We ran out of milk." },
  { type: "idiom", en: "look after ~", ja: "~の面倒を見る", ex: "Can you look after my dog?" },
  { type: "idiom", en: "be famous for ~", ja: "~で有名である", ex: "Kyoto is famous for its temples." },
  { type: "idiom", en: "as soon as ~", ja: "~するとすぐに", ex: "Call me as soon as you arrive." },
  { type: "idiom", en: "in front of ~", ja: "~の前に", ex: "He stood in front of the door." },
  { type: "idiom", en: "at least", ja: "少なくとも", ex: "Drink at least two liters of water." },
  { type: "idiom", en: "by the way", ja: "ところで", ex: "By the way, where do you live?" },
  { type: "idiom", en: "on time", ja: "時間通りに", ex: "The train arrived on time." },
  { type: "idiom", en: "take part in ~", ja: "~に参加する", ex: "I will take part in the contest." },
  { type: "idiom", en: "make sure", ja: "確かめる", ex: "Make sure you lock the door." },
  { type: "idiom", en: "turn down ~", ja: "~を断る、音量を下げる", ex: "She turned down the job offer." },
  { type: "idiom", en: "look up ~", ja: "~を調べる", ex: "Look up the word in a dictionary." },
  { type: "idiom", en: "used to ~", ja: "以前は~したものだ", ex: "I used to play tennis." },
  { type: "idiom", en: "be good at ~", ja: "~が得意である", ex: "She is good at math." },
  { type: "idiom", en: "in the end", ja: "最後には", ex: "In the end, we won the game." },
  { type: "idiom", en: "on purpose", ja: "わざと", ex: "He broke it on purpose." },
  { type: "idiom", en: "keep in touch", ja: "連絡を取り合う", ex: "Let's keep in touch." },
  { type: "idiom", en: "instead of ~", ja: "~の代わりに", ex: "Have tea instead of coffee." },
  { type: "idiom", en: "as a result", ja: "その結果", ex: "As a result, he passed the exam." },
  { type: "idiom", en: "depend on ~", ja: "~次第である、頼る", ex: "It depends on the weather." },
  { type: "idiom", en: "figure out ~", ja: "~を理解する、解決する", ex: "I can't figure out this problem." },
  { type: "idiom", en: "for example", ja: "たとえば", ex: "For example, cats are popular pets." },
  { type: "idiom", en: "sooner or later", ja: "遅かれ早かれ", ex: "Sooner or later, you'll understand." },
];
