// lv: TOEIC点数帯のレベル(1〜5) / type: "word" = 英単語, "idiom" = 熟語
const LEVELS = [
  { id: 1, label: "〜400", name: "入門" },
  { id: 2, label: "400〜", name: "基礎" },
  { id: 3, label: "600〜", name: "標準" },
  { id: 4, label: "730〜", name: "上級" },
  { id: 5, label: "860〜", name: "最上級" },
];
const WORDS = [
  {"lv": 1, "type": "word", "en": "avoid", "ja": "避ける", "ex": "You should avoid eating too much sugar."},
  {"lv": 1, "type": "word", "en": "borrow", "ja": "借りる", "ex": "Can I borrow your pen?"},
  {"lv": 1, "type": "word", "en": "century", "ja": "世紀", "ex": "This house was built a century ago."},
  {"lv": 1, "type": "word", "en": "decide", "ja": "決める", "ex": "I decided to study abroad."},
  {"lv": 1, "type": "word", "en": "delicious", "ja": "とてもおいしい", "ex": "This cake is delicious."},
  {"lv": 1, "type": "word", "en": "enough", "ja": "十分な", "ex": "Do we have enough time?"},
  {"lv": 1, "type": "word", "en": "foreign", "ja": "外国の", "ex": "She speaks three foreign languages."},
  {"lv": 1, "type": "word", "en": "honest", "ja": "正直な", "ex": "An honest answer is best."},
  {"lv": 1, "type": "word", "en": "imagine", "ja": "想像する", "ex": "Imagine you are on a beach."},
  {"lv": 1, "type": "word", "en": "receive", "ja": "受け取る", "ex": "I received a letter yesterday."},
  {"lv": 1, "type": "word", "en": "arrive", "ja": "到着する", "ex": "The train arrives at noon."},
  {"lv": 1, "type": "word", "en": "appointment", "ja": "約束、予約", "ex": "I have an appointment at three."},
  {"lv": 1, "type": "word", "en": "customer", "ja": "顧客", "ex": "The customer asked a question."},
  {"lv": 1, "type": "word", "en": "office", "ja": "事務所", "ex": "She works in a small office."},
  {"lv": 1, "type": "word", "en": "meeting", "ja": "会議", "ex": "We have a meeting on Monday."},
  {"lv": 1, "type": "word", "en": "schedule", "ja": "予定", "ex": "What is your schedule today?"},
  {"lv": 1, "type": "word", "en": "ticket", "ja": "切符", "ex": "I bought a ticket online."},
  {"lv": 1, "type": "word", "en": "travel", "ja": "旅行する", "ex": "They travel to Europe every summer."},
  {"lv": 1, "type": "word", "en": "return", "ja": "戻る", "ex": "He returned home late."},
  {"lv": 1, "type": "word", "en": "visit", "ja": "訪問する", "ex": "I will visit my uncle tomorrow."},
  {"lv": 1, "type": "word", "en": "reserve", "ja": "予約する", "ex": "I reserved a table for four."},
  {"lv": 1, "type": "word", "en": "repair", "ja": "修理する", "ex": "He repaired my bike."},
  {"lv": 1, "type": "word", "en": "pay", "ja": "支払う", "ex": "I'll pay by credit card."},
  {"lv": 1, "type": "word", "en": "cheap", "ja": "安い", "ex": "This shirt is very cheap."},
  {"lv": 1, "type": "word", "en": "expensive", "ja": "高価な", "ex": "The hotel was too expensive."},
  {"lv": 1, "type": "word", "en": "busy", "ja": "忙しい", "ex": "I'm busy this afternoon."},
  {"lv": 1, "type": "word", "en": "quiet", "ja": "静かな", "ex": "Please be quiet in the library."},
  {"lv": 1, "type": "word", "en": "crowded", "ja": "混雑した", "ex": "The station was crowded."},
  {"lv": 1, "type": "word", "en": "free", "ja": "無料の", "ex": "Coffee is free for members."},
  {"lv": 1, "type": "word", "en": "message", "ja": "伝言", "ex": "I left a message for you."},
  {"lv": 1, "type": "word", "en": "follow", "ja": "ついて行く", "ex": "Please follow me."},
  {"lv": 1, "type": "word", "en": "invite", "ja": "招待する", "ex": "She invited me to her party."},
  {"lv": 1, "type": "word", "en": "gift", "ja": "贈り物", "ex": "This is a gift for you."},
  {"lv": 1, "type": "word", "en": "meal", "ja": "食事", "ex": "We had a big meal."},
  {"lv": 1, "type": "word", "en": "sell", "ja": "売る", "ex": "They sell fresh fruit here."},
  {"lv": 1, "type": "word", "en": "leave", "ja": "出発する、去る", "ex": "The bus leaves at eight."},
  {"lv": 1, "type": "word", "en": "weather", "ja": "天気", "ex": "The weather is nice today."},
  {"lv": 1, "type": "word", "en": "wait", "ja": "待つ", "ex": "Please wait here."},
  {"lv": 1, "type": "word", "en": "choose", "ja": "選ぶ", "ex": "You can choose any color."},
  {"lv": 1, "type": "word", "en": "practice", "ja": "練習する", "ex": "I practice English every day."},
  {"lv": 1, "type": "word", "en": "important", "ja": "重要な", "ex": "This is an important document."},
  {"lv": 1, "type": "word", "en": "difficult", "ja": "難しい", "ex": "The test was difficult."},
  {"lv": 1, "type": "word", "en": "comfortable", "ja": "快適な", "ex": "This chair is comfortable."},
  {"lv": 1, "type": "idiom", "en": "look forward to ~", "ja": "~を楽しみに待つ", "ex": "I look forward to seeing you."},
  {"lv": 1, "type": "idiom", "en": "give up", "ja": "あきらめる", "ex": "Never give up on your dreams."},
  {"lv": 1, "type": "idiom", "en": "take care of ~", "ja": "~の世話をする", "ex": "She takes care of her little brother."},
  {"lv": 1, "type": "idiom", "en": "find out", "ja": "見つけ出す、知る", "ex": "I found out the truth."},
  {"lv": 1, "type": "idiom", "en": "get along with ~", "ja": "~と仲良くやる", "ex": "I get along with my classmates."},
  {"lv": 1, "type": "idiom", "en": "look after ~", "ja": "~の面倒を見る", "ex": "Can you look after my dog?"},
  {"lv": 1, "type": "idiom", "en": "be famous for ~", "ja": "~で有名である", "ex": "Kyoto is famous for its temples."},
  {"lv": 1, "type": "idiom", "en": "as soon as ~", "ja": "~するとすぐに", "ex": "Call me as soon as you arrive."},
  {"lv": 1, "type": "idiom", "en": "in front of ~", "ja": "~の前に", "ex": "He stood in front of the door."},
  {"lv": 1, "type": "idiom", "en": "at least", "ja": "少なくとも", "ex": "Drink at least two liters of water."},
  {"lv": 1, "type": "idiom", "en": "by the way", "ja": "ところで", "ex": "By the way, where do you live?"},
  {"lv": 1, "type": "idiom", "en": "on time", "ja": "時間通りに", "ex": "The train arrived on time."},
  {"lv": 1, "type": "idiom", "en": "look up ~", "ja": "~を調べる", "ex": "Look up the word in a dictionary."},
  {"lv": 1, "type": "idiom", "en": "used to ~", "ja": "以前は~したものだ", "ex": "I used to play tennis."},
  {"lv": 1, "type": "idiom", "en": "be good at ~", "ja": "~が得意である", "ex": "She is good at math."},
  {"lv": 1, "type": "idiom", "en": "instead of ~", "ja": "~の代わりに", "ex": "Have tea instead of coffee."},
  {"lv": 1, "type": "idiom", "en": "for example", "ja": "たとえば", "ex": "For example, cats are popular pets."},
  {"lv": 1, "type": "idiom", "en": "a lot of ~", "ja": "たくさんの~", "ex": "She has a lot of friends."},
  {"lv": 1, "type": "idiom", "en": "at home", "ja": "家で", "ex": "I stayed at home all day."},
  {"lv": 1, "type": "idiom", "en": "at first", "ja": "最初は", "ex": "At first, I didn't like it."},
  {"lv": 1, "type": "idiom", "en": "all the time", "ja": "いつも、ずっと", "ex": "He plays games all the time."},
  {"lv": 1, "type": "idiom", "en": "be ready for ~", "ja": "~の準備ができている", "ex": "Are you ready for the trip?"},
  {"lv": 1, "type": "idiom", "en": "come back", "ja": "戻ってくる", "ex": "Come back before dark."},
  {"lv": 1, "type": "idiom", "en": "get up", "ja": "起きる", "ex": "I get up at six."},
  {"lv": 1, "type": "idiom", "en": "go out", "ja": "外出する", "ex": "Let's go out for dinner."},
  {"lv": 1, "type": "idiom", "en": "go on", "ja": "続く、続ける", "ex": "Please go on with your story."},
  {"lv": 1, "type": "idiom", "en": "hear from ~", "ja": "~から連絡をもらう", "ex": "I heard from my sister today."},
  {"lv": 1, "type": "idiom", "en": "in a hurry", "ja": "急いで", "ex": "She left in a hurry."},
  {"lv": 1, "type": "idiom", "en": "in time", "ja": "間に合って", "ex": "We arrived in time for the movie."},
  {"lv": 1, "type": "idiom", "en": "look for ~", "ja": "~を探す", "ex": "I'm looking for my keys."},
  {"lv": 1, "type": "idiom", "en": "pick up ~", "ja": "~を拾う、迎えに行く", "ex": "I'll pick you up at the station."},
  {"lv": 1, "type": "idiom", "en": "put on ~", "ja": "~を身につける", "ex": "Put on your coat."},
  {"lv": 1, "type": "idiom", "en": "sit down", "ja": "座る", "ex": "Please sit down."},
  {"lv": 1, "type": "idiom", "en": "take off ~", "ja": "脱ぐ、離陸する", "ex": "Take off your shoes here."},
  {"lv": 1, "type": "idiom", "en": "thank you for ~", "ja": "~をありがとう", "ex": "Thank you for your help."},
  {"lv": 1, "type": "idiom", "en": "try on ~", "ja": "~を試着する", "ex": "Can I try on this jacket?"},
  {"lv": 1, "type": "idiom", "en": "wait for ~", "ja": "~を待つ", "ex": "I'm waiting for a bus."},
  {"lv": 2, "type": "word", "en": "achieve", "ja": "達成する", "ex": "She worked hard to achieve her goal."},
  {"lv": 2, "type": "word", "en": "adapt", "ja": "適応する", "ex": "Animals adapt to their environment."},
  {"lv": 2, "type": "word", "en": "advantage", "ja": "利点", "ex": "Speaking English is a big advantage."},
  {"lv": 2, "type": "word", "en": "ancient", "ja": "古代の", "ex": "We visited an ancient temple."},
  {"lv": 2, "type": "word", "en": "appreciate", "ja": "感謝する", "ex": "I really appreciate your help."},
  {"lv": 2, "type": "word", "en": "attempt", "ja": "試みる", "ex": "He attempted to climb the mountain."},
  {"lv": 2, "type": "word", "en": "benefit", "ja": "利益", "ex": "Exercise has many health benefits."},
  {"lv": 2, "type": "word", "en": "challenge", "ja": "挑戦", "ex": "Learning a language is a challenge."},
  {"lv": 2, "type": "word", "en": "communicate", "ja": "意思疎通する", "ex": "We communicate by email."},
  {"lv": 2, "type": "word", "en": "compare", "ja": "比較する", "ex": "Don't compare yourself with others."},
  {"lv": 2, "type": "word", "en": "confident", "ja": "自信のある", "ex": "She is confident about the test."},
  {"lv": 2, "type": "word", "en": "consider", "ja": "よく考える", "ex": "Please consider my offer."},
  {"lv": 2, "type": "word", "en": "create", "ja": "創造する", "ex": "Artists create beautiful things."},
  {"lv": 2, "type": "word", "en": "describe", "ja": "説明する", "ex": "Can you describe the man you saw?"},
  {"lv": 2, "type": "word", "en": "discover", "ja": "発見する", "ex": "Scientists discovered a new planet."},
  {"lv": 2, "type": "word", "en": "environment", "ja": "環境", "ex": "We must protect the environment."},
  {"lv": 2, "type": "word", "en": "experience", "ja": "経験", "ex": "He has a lot of teaching experience."},
  {"lv": 2, "type": "word", "en": "familiar", "ja": "よく知っている", "ex": "That song sounds familiar."},
  {"lv": 2, "type": "word", "en": "generous", "ja": "気前のよい", "ex": "He is generous to everyone."},
  {"lv": 2, "type": "word", "en": "improve", "ja": "上達させる", "ex": "I want to improve my English."},
  {"lv": 2, "type": "word", "en": "necessary", "ja": "必要な", "ex": "Is it necessary to go today?"},
  {"lv": 2, "type": "word", "en": "opportunity", "ja": "機会", "ex": "This is a great opportunity."},
  {"lv": 2, "type": "word", "en": "prepare", "ja": "準備する", "ex": "I need to prepare for the exam."},
  {"lv": 2, "type": "word", "en": "recommend", "ja": "勧める", "ex": "I recommend this restaurant."},
  {"lv": 2, "type": "word", "en": "reduce", "ja": "減らす", "ex": "We should reduce waste."},
  {"lv": 2, "type": "word", "en": "responsible", "ja": "責任のある", "ex": "He is responsible for the project."},
  {"lv": 2, "type": "word", "en": "separate", "ja": "分ける", "ex": "Please separate the trash."},
  {"lv": 2, "type": "word", "en": "succeed", "ja": "成功する", "ex": "You will succeed if you try."},
  {"lv": 2, "type": "word", "en": "suggest", "ja": "提案する", "ex": "I suggest taking a break."},
  {"lv": 2, "type": "word", "en": "tradition", "ja": "伝統", "ex": "It is a Japanese tradition."},
  {"lv": 2, "type": "word", "en": "valuable", "ja": "貴重な", "ex": "Time is valuable."},
  {"lv": 2, "type": "word", "en": "account", "ja": "口座", "ex": "I opened a bank account."},
  {"lv": 2, "type": "word", "en": "agree", "ja": "同意する", "ex": "I agree with your idea."},
  {"lv": 2, "type": "word", "en": "allow", "ja": "許可する", "ex": "Photos are not allowed here."},
  {"lv": 2, "type": "word", "en": "amount", "ja": "量、金額", "ex": "A small amount of salt is enough."},
  {"lv": 2, "type": "word", "en": "article", "ja": "記事", "ex": "I read an interesting article."},
  {"lv": 2, "type": "word", "en": "attend", "ja": "出席する", "ex": "She attended the meeting."},
  {"lv": 2, "type": "word", "en": "available", "ja": "利用できる", "ex": "Is this room available tonight?"},
  {"lv": 2, "type": "word", "en": "award", "ja": "賞", "ex": "He won an award for his work."},
  {"lv": 2, "type": "word", "en": "budget", "ja": "予算", "ex": "We have a small budget."},
  {"lv": 2, "type": "word", "en": "candidate", "ja": "候補者", "ex": "There are three candidates."},
  {"lv": 2, "type": "word", "en": "cancel", "ja": "取り消す", "ex": "They canceled the flight."},
  {"lv": 2, "type": "word", "en": "charge", "ja": "請求する", "ex": "They charged me ten dollars."},
  {"lv": 2, "type": "word", "en": "colleague", "ja": "同僚", "ex": "I had lunch with a colleague."},
  {"lv": 2, "type": "word", "en": "complain", "ja": "不満を言う", "ex": "Customers complained about the noise."},
  {"lv": 2, "type": "word", "en": "contact", "ja": "連絡する", "ex": "Please contact me by email."},
  {"lv": 2, "type": "word", "en": "deliver", "ja": "配達する", "ex": "They deliver pizza in 30 minutes."},
  {"lv": 2, "type": "word", "en": "discount", "ja": "割引", "ex": "You can get a 10% discount."},
  {"lv": 2, "type": "word", "en": "employee", "ja": "従業員", "ex": "The company has 50 employees."},
  {"lv": 2, "type": "word", "en": "expect", "ja": "予期する", "ex": "I expect him to come soon."},
  {"lv": 2, "type": "word", "en": "increase", "ja": "増加する", "ex": "Sales increased last month."},
  {"lv": 2, "type": "word", "en": "include", "ja": "含む", "ex": "The price includes tax."},
  {"lv": 2, "type": "word", "en": "position", "ja": "職、地位", "ex": "He applied for a new position."},
  {"lv": 2, "type": "word", "en": "product", "ja": "製品", "ex": "This product is very popular."},
  {"lv": 2, "type": "idiom", "en": "put off", "ja": "延期する", "ex": "Don't put off your homework."},
  {"lv": 2, "type": "idiom", "en": "come up with ~", "ja": "~を思いつく", "ex": "He came up with a good idea."},
  {"lv": 2, "type": "idiom", "en": "run out of ~", "ja": "~を使い果たす", "ex": "We ran out of milk."},
  {"lv": 2, "type": "idiom", "en": "take part in ~", "ja": "~に参加する", "ex": "I will take part in the contest."},
  {"lv": 2, "type": "idiom", "en": "make sure", "ja": "確かめる", "ex": "Make sure you lock the door."},
  {"lv": 2, "type": "idiom", "en": "turn down ~", "ja": "~を断る、音量を下げる", "ex": "She turned down the job offer."},
  {"lv": 2, "type": "idiom", "en": "in the end", "ja": "最後には", "ex": "In the end, we won the game."},
  {"lv": 2, "type": "idiom", "en": "on purpose", "ja": "わざと", "ex": "He broke it on purpose."},
  {"lv": 2, "type": "idiom", "en": "keep in touch", "ja": "連絡を取り合う", "ex": "Let's keep in touch."},
  {"lv": 2, "type": "idiom", "en": "as a result", "ja": "その結果", "ex": "As a result, he passed the exam."},
  {"lv": 2, "type": "idiom", "en": "depend on ~", "ja": "~次第である、頼る", "ex": "It depends on the weather."},
  {"lv": 2, "type": "idiom", "en": "figure out ~", "ja": "~を理解する、解決する", "ex": "I can't figure out this problem."},
  {"lv": 2, "type": "idiom", "en": "sooner or later", "ja": "遅かれ早かれ", "ex": "Sooner or later, you'll understand."},
  {"lv": 2, "type": "idiom", "en": "according to ~", "ja": "~によると", "ex": "According to the news, it will rain."},
  {"lv": 2, "type": "idiom", "en": "a couple of ~", "ja": "2、3の~", "ex": "I waited for a couple of minutes."},
  {"lv": 2, "type": "idiom", "en": "as well as ~", "ja": "~と同様に", "ex": "She speaks French as well as English."},
  {"lv": 2, "type": "idiom", "en": "be able to ~", "ja": "~できる", "ex": "He is able to swim well."},
  {"lv": 2, "type": "idiom", "en": "be supposed to ~", "ja": "~することになっている", "ex": "You are supposed to wait here."},
  {"lv": 2, "type": "idiom", "en": "because of ~", "ja": "~のせいで", "ex": "We stayed home because of the rain."},
  {"lv": 2, "type": "idiom", "en": "each other", "ja": "お互い", "ex": "They helped each other."},
  {"lv": 2, "type": "idiom", "en": "fill out ~", "ja": "~に記入する", "ex": "Please fill out this form."},
  {"lv": 2, "type": "idiom", "en": "hand in ~", "ja": "~を提出する", "ex": "Hand in your report by Friday."},
  {"lv": 2, "type": "idiom", "en": "in charge of ~", "ja": "~を担当して", "ex": "She is in charge of sales."},
  {"lv": 2, "type": "idiom", "en": "let ~ know", "ja": "~に知らせる", "ex": "Let me know if you need help."},
  {"lv": 2, "type": "idiom", "en": "on sale", "ja": "特売中で", "ex": "All shoes are on sale."},
  {"lv": 2, "type": "idiom", "en": "point out ~", "ja": "~を指摘する", "ex": "He pointed out a mistake."},
  {"lv": 3, "type": "word", "en": "acquire", "ja": "獲得する", "ex": "The company acquired a new factory."},
  {"lv": 3, "type": "word", "en": "adjust", "ja": "調節する", "ex": "I adjusted the chair height."},
  {"lv": 3, "type": "word", "en": "advertise", "ja": "宣伝する", "ex": "They advertise on television."},
  {"lv": 3, "type": "word", "en": "agenda", "ja": "議題", "ex": "What is on the agenda today?"},
  {"lv": 3, "type": "word", "en": "applicant", "ja": "応募者", "ex": "Each applicant must submit a résumé."},
  {"lv": 3, "type": "word", "en": "approve", "ja": "承認する", "ex": "The manager approved the plan."},
  {"lv": 3, "type": "word", "en": "assign", "ja": "割り当てる", "ex": "She was assigned to a new project."},
  {"lv": 3, "type": "word", "en": "attach", "ja": "添付する", "ex": "I attached the file to this email."},
  {"lv": 3, "type": "word", "en": "authorize", "ja": "認可する", "ex": "Only managers can authorize payments."},
  {"lv": 3, "type": "word", "en": "brochure", "ja": "パンフレット", "ex": "Please take a brochure."},
  {"lv": 3, "type": "word", "en": "complimentary", "ja": "無料進呈の", "ex": "Complimentary coffee is served."},
  {"lv": 3, "type": "word", "en": "conference", "ja": "大会、協議会", "ex": "He spoke at an international conference."},
  {"lv": 3, "type": "word", "en": "confirm", "ja": "(事実を)確認する", "ex": "Please confirm your reservation."},
  {"lv": 3, "type": "word", "en": "contract", "ja": "契約", "ex": "They signed a two-year contract."},
  {"lv": 3, "type": "word", "en": "corporation", "ja": "企業", "ex": "It is a large corporation."},
  {"lv": 3, "type": "word", "en": "deadline", "ja": "締め切り", "ex": "The deadline is next Friday."},
  {"lv": 3, "type": "word", "en": "delay", "ja": "遅延", "ex": "There was a delay due to snow."},
  {"lv": 3, "type": "word", "en": "department", "ja": "部署", "ex": "She works in the sales department."},
  {"lv": 3, "type": "word", "en": "distribute", "ja": "配布する", "ex": "Volunteers distributed free water."},
  {"lv": 3, "type": "word", "en": "effective", "ja": "効果的な", "ex": "This is an effective method."},
  {"lv": 3, "type": "word", "en": "enclose", "ja": "同封する", "ex": "I enclosed a check with the letter."},
  {"lv": 3, "type": "word", "en": "estimate", "ja": "見積もる", "ex": "We estimate the cost at $500."},
  {"lv": 3, "type": "word", "en": "expand", "ja": "拡大する", "ex": "The firm plans to expand overseas."},
  {"lv": 3, "type": "word", "en": "facility", "ja": "施設", "ex": "The facility is open to everyone."},
  {"lv": 3, "type": "word", "en": "fee", "ja": "料金", "ex": "There is a small entrance fee."},
  {"lv": 3, "type": "word", "en": "inquiry", "ja": "問い合わせ", "ex": "I made an inquiry about the job."},
  {"lv": 3, "type": "word", "en": "install", "ja": "設置する", "ex": "They installed a new printer."},
  {"lv": 3, "type": "word", "en": "inventory", "ja": "在庫", "ex": "We check our inventory weekly."},
  {"lv": 3, "type": "word", "en": "invoice", "ja": "請求書", "ex": "The invoice was sent yesterday."},
  {"lv": 3, "type": "word", "en": "maintain", "ja": "維持する", "ex": "It is hard to maintain old machines."},
  {"lv": 3, "type": "word", "en": "merchandise", "ja": "商品", "ex": "The store sells sports merchandise."},
  {"lv": 3, "type": "word", "en": "negotiate", "ja": "交渉する", "ex": "They negotiated a better price."},
  {"lv": 3, "type": "word", "en": "occupy", "ja": "占める", "ex": "The office occupies two floors."},
  {"lv": 3, "type": "word", "en": "order", "ja": "注文", "ex": "I placed an order online."},
  {"lv": 3, "type": "word", "en": "overtime", "ja": "残業", "ex": "He worked overtime last night."},
  {"lv": 3, "type": "word", "en": "participate", "ja": "参加する", "ex": "Everyone can participate in the event."},
  {"lv": 3, "type": "word", "en": "personnel", "ja": "人事、職員", "ex": "Personnel changes were announced."},
  {"lv": 3, "type": "word", "en": "promote", "ja": "昇進させる、促進する", "ex": "She was promoted to manager."},
  {"lv": 3, "type": "word", "en": "purchase", "ja": "購入する", "ex": "I purchased a new laptop."},
  {"lv": 3, "type": "word", "en": "quarter", "ja": "四半期", "ex": "Profits rose in the third quarter."},
  {"lv": 3, "type": "word", "en": "refund", "ja": "払い戻し", "ex": "I asked for a refund."},
  {"lv": 3, "type": "word", "en": "register", "ja": "登録する", "ex": "Please register at the front desk."},
  {"lv": 3, "type": "word", "en": "renew", "ja": "更新する", "ex": "I need to renew my passport."},
  {"lv": 3, "type": "word", "en": "replace", "ja": "取り替える", "ex": "They replaced the old computers."},
  {"lv": 3, "type": "word", "en": "require", "ja": "必要とする", "ex": "This job requires experience."},
  {"lv": 3, "type": "word", "en": "revenue", "ja": "収入", "ex": "Annual revenue reached $2 million."},
  {"lv": 3, "type": "word", "en": "shipment", "ja": "出荷、積荷", "ex": "The shipment arrived this morning."},
  {"lv": 3, "type": "word", "en": "supplier", "ja": "供給業者", "ex": "We changed our supplier."},
  {"lv": 3, "type": "word", "en": "warranty", "ja": "保証", "ex": "The laptop has a one-year warranty."},
  {"lv": 3, "type": "word", "en": "vacancy", "ja": "空き、欠員", "ex": "There is a vacancy in our team."},
  {"lv": 3, "type": "idiom", "en": "as a matter of fact", "ja": "実は", "ex": "As a matter of fact, I've met him."},
  {"lv": 3, "type": "idiom", "en": "at the moment", "ja": "現在のところ", "ex": "He is out of the office at the moment."},
  {"lv": 3, "type": "idiom", "en": "be aware of ~", "ja": "~に気づいている", "ex": "Are you aware of the problem?"},
  {"lv": 3, "type": "idiom", "en": "be responsible for ~", "ja": "~に責任がある", "ex": "She is responsible for training."},
  {"lv": 3, "type": "idiom", "en": "be eligible for ~", "ja": "~の資格がある", "ex": "Students are eligible for a discount."},
  {"lv": 3, "type": "idiom", "en": "be scheduled to ~", "ja": "~する予定である", "ex": "The talk is scheduled to start at ten."},
  {"lv": 3, "type": "idiom", "en": "bring up ~", "ja": "~を持ち出す", "ex": "He brought up a new idea."},
  {"lv": 3, "type": "idiom", "en": "call off ~", "ja": "~を中止する", "ex": "They called off the picnic."},
  {"lv": 3, "type": "idiom", "en": "carry out ~", "ja": "~を実行する", "ex": "We carried out a survey."},
  {"lv": 3, "type": "idiom", "en": "cut down on ~", "ja": "~を減らす", "ex": "We should cut down on costs."},
  {"lv": 3, "type": "idiom", "en": "deal with ~", "ja": "~に対処する", "ex": "She dealt with the complaint well."},
  {"lv": 3, "type": "idiom", "en": "end up ~ing", "ja": "結局~することになる", "ex": "I ended up staying home."},
  {"lv": 3, "type": "idiom", "en": "fall behind", "ja": "遅れをとる", "ex": "We fell behind schedule."},
  {"lv": 3, "type": "idiom", "en": "follow up on ~", "ja": "~をさらに追跡する", "ex": "I'll follow up on your request."},
  {"lv": 3, "type": "idiom", "en": "get in touch with ~", "ja": "~と連絡を取る", "ex": "Get in touch with our office."},
  {"lv": 3, "type": "idiom", "en": "in advance", "ja": "前もって", "ex": "Please book in advance."},
  {"lv": 3, "type": "idiom", "en": "in addition to ~", "ja": "~に加えて", "ex": "In addition to salary, we offer a bonus."},
  {"lv": 3, "type": "idiom", "en": "in case of ~", "ja": "~の場合には", "ex": "In case of fire, use the stairs."},
  {"lv": 3, "type": "idiom", "en": "on behalf of ~", "ja": "~を代表して", "ex": "I speak on behalf of the team."},
  {"lv": 3, "type": "idiom", "en": "on business", "ja": "仕事で", "ex": "He is traveling on business."},
  {"lv": 3, "type": "idiom", "en": "out of stock", "ja": "在庫切れで", "ex": "That item is out of stock."},
  {"lv": 3, "type": "idiom", "en": "pass out ~", "ja": "~を配る", "ex": "He passed out the handouts."},
  {"lv": 3, "type": "idiom", "en": "prior to ~", "ja": "~より前に", "ex": "Arrive prior to the meeting."},
  {"lv": 3, "type": "idiom", "en": "set up ~", "ja": "~を設立する", "ex": "They set up a new company."},
  {"lv": 3, "type": "idiom", "en": "sign up for ~", "ja": "~に登録する", "ex": "I signed up for a class."},
  {"lv": 3, "type": "idiom", "en": "take over ~", "ja": "~を引き継ぐ", "ex": "She took over the project."},
  {"lv": 3, "type": "idiom", "en": "turn in ~", "ja": "~を提出する", "ex": "Turn in your form today."},
  {"lv": 3, "type": "idiom", "en": "under construction", "ja": "工事中で", "ex": "The bridge is under construction."},
  {"lv": 3, "type": "idiom", "en": "work on ~", "ja": "~に取り組む", "ex": "I'm working on a report."},
  {"lv": 3, "type": "idiom", "en": "with regard to ~", "ja": "~に関して", "ex": "With regard to your question, yes."},
  {"lv": 4, "type": "word", "en": "accommodate", "ja": "収容する、便宜を図る", "ex": "The hall can accommodate 500 people."},
  {"lv": 4, "type": "word", "en": "accumulate", "ja": "蓄積する", "ex": "Dust accumulated on the shelves."},
  {"lv": 4, "type": "word", "en": "acknowledge", "ja": "認める、受領を知らせる", "ex": "Please acknowledge receipt of this email."},
  {"lv": 4, "type": "word", "en": "allocate", "ja": "配分する", "ex": "We allocated funds to the project."},
  {"lv": 4, "type": "word", "en": "amend", "ja": "修正する", "ex": "They amended the contract."},
  {"lv": 4, "type": "word", "en": "anticipate", "ja": "見越す", "ex": "We anticipate strong demand."},
  {"lv": 4, "type": "word", "en": "appraisal", "ja": "査定", "ex": "The house had an appraisal last week."},
  {"lv": 4, "type": "word", "en": "assess", "ja": "評価する", "ex": "We need to assess the risks."},
  {"lv": 4, "type": "word", "en": "audit", "ja": "監査", "ex": "The audit begins next week."},
  {"lv": 4, "type": "word", "en": "beneficial", "ja": "有益な", "ex": "The change was beneficial to everyone."},
  {"lv": 4, "type": "word", "en": "capacity", "ja": "収容能力", "ex": "The stadium has a capacity of 40,000."},
  {"lv": 4, "type": "word", "en": "clarify", "ja": "明確にする", "ex": "Could you clarify your point?"},
  {"lv": 4, "type": "word", "en": "commence", "ja": "開始する", "ex": "The ceremony will commence at noon."},
  {"lv": 4, "type": "word", "en": "compensate", "ja": "補償する", "ex": "The firm compensated the workers."},
  {"lv": 4, "type": "word", "en": "compliance", "ja": "法令遵守", "ex": "Compliance with rules is required."},
  {"lv": 4, "type": "word", "en": "comprehensive", "ja": "包括的な", "ex": "We offer comprehensive insurance."},
  {"lv": 4, "type": "word", "en": "consecutive", "ja": "連続した", "ex": "It rained for three consecutive days."},
  {"lv": 4, "type": "word", "en": "consequently", "ja": "その結果", "ex": "Consequently, sales went up."},
  {"lv": 4, "type": "word", "en": "considerable", "ja": "かなりの", "ex": "It saved a considerable amount of time."},
  {"lv": 4, "type": "word", "en": "consolidate", "ja": "統合する", "ex": "They consolidated two departments."},
  {"lv": 4, "type": "word", "en": "constraint", "ja": "制約", "ex": "Budget constraints limited our plans."},
  {"lv": 4, "type": "word", "en": "curtail", "ja": "削減する", "ex": "The firm curtailed its spending."},
  {"lv": 4, "type": "word", "en": "designate", "ja": "指名する", "ex": "She was designated team leader."},
  {"lv": 4, "type": "word", "en": "diligent", "ja": "勤勉な", "ex": "He is a diligent worker."},
  {"lv": 4, "type": "word", "en": "discrepancy", "ja": "食い違い", "ex": "We found a discrepancy in the figures."},
  {"lv": 4, "type": "word", "en": "dispatch", "ja": "発送する", "ex": "The goods were dispatched today."},
  {"lv": 4, "type": "word", "en": "enforce", "ja": "施行する", "ex": "The city enforces the new law."},
  {"lv": 4, "type": "word", "en": "enhance", "ja": "高める", "ex": "This tool enhances productivity."},
  {"lv": 4, "type": "word", "en": "ensure", "ja": "確実にする", "ex": "Please ensure that the door is locked."},
  {"lv": 4, "type": "word", "en": "expire", "ja": "期限が切れる", "ex": "My passport expires in May."},
  {"lv": 4, "type": "word", "en": "feasible", "ja": "実行できる", "ex": "Is the plan feasible?"},
  {"lv": 4, "type": "word", "en": "fluctuate", "ja": "変動する", "ex": "Prices fluctuate throughout the year."},
  {"lv": 4, "type": "word", "en": "forecast", "ja": "予測", "ex": "The sales forecast is positive."},
  {"lv": 4, "type": "word", "en": "furnish", "ja": "備え付ける", "ex": "The room is furnished with a desk."},
  {"lv": 4, "type": "word", "en": "implement", "ja": "実施する", "ex": "They implemented a new system."},
  {"lv": 4, "type": "word", "en": "incentive", "ja": "報奨", "ex": "Employees get a bonus as an incentive."},
  {"lv": 4, "type": "word", "en": "inevitable", "ja": "避けられない", "ex": "Change is inevitable."},
  {"lv": 4, "type": "word", "en": "initiate", "ja": "着手する", "ex": "She initiated a new project."},
  {"lv": 4, "type": "word", "en": "liability", "ja": "責任、負債", "ex": "The company accepts no liability."},
  {"lv": 4, "type": "word", "en": "mandatory", "ja": "義務的な", "ex": "Attendance is mandatory."},
  {"lv": 4, "type": "word", "en": "mutual", "ja": "相互の", "ex": "We reached a mutual agreement."},
  {"lv": 4, "type": "word", "en": "obsolete", "ja": "時代遅れの", "ex": "This software is obsolete."},
  {"lv": 4, "type": "word", "en": "outstanding", "ja": "未払いの、傑出した", "ex": "There is an outstanding balance."},
  {"lv": 4, "type": "word", "en": "perishable", "ja": "傷みやすい", "ex": "Perishable food must be kept cold."},
  {"lv": 4, "type": "word", "en": "predecessor", "ja": "前任者", "ex": "My predecessor left detailed notes."},
  {"lv": 4, "type": "word", "en": "prohibit", "ja": "禁止する", "ex": "Smoking is prohibited here."},
  {"lv": 4, "type": "word", "en": "proficient", "ja": "熟達した", "ex": "She is proficient in Spanish."},
  {"lv": 4, "type": "word", "en": "relocate", "ja": "移転する", "ex": "The office will relocate next year."},
  {"lv": 4, "type": "word", "en": "renovate", "ja": "改装する", "ex": "They renovated the hotel lobby."},
  {"lv": 4, "type": "word", "en": "reputable", "ja": "評判のよい", "ex": "It is a reputable company."},
  {"lv": 4, "type": "word", "en": "substantial", "ja": "相当な", "ex": "They made a substantial profit."},
  {"lv": 4, "type": "word", "en": "subsidiary", "ja": "子会社", "ex": "It is a subsidiary of a large firm."},
  {"lv": 4, "type": "word", "en": "supervise", "ja": "監督する", "ex": "He supervises ten employees."},
  {"lv": 4, "type": "word", "en": "tentative", "ja": "暫定的な", "ex": "We made a tentative plan."},
  {"lv": 4, "type": "word", "en": "unprecedented", "ja": "前例のない", "ex": "Sales reached an unprecedented level."},
  {"lv": 4, "type": "idiom", "en": "abide by ~", "ja": "~を守る", "ex": "You must abide by the rules."},
  {"lv": 4, "type": "idiom", "en": "account for ~", "ja": "~を説明する、占める", "ex": "Exports account for 40% of sales."},
  {"lv": 4, "type": "idiom", "en": "be liable for ~", "ja": "~に責任を負う", "ex": "The owner is liable for damage."},
  {"lv": 4, "type": "idiom", "en": "be subject to ~", "ja": "~の対象となる", "ex": "Prices are subject to change."},
  {"lv": 4, "type": "idiom", "en": "by means of ~", "ja": "~によって", "ex": "Pay by means of a credit card."},
  {"lv": 4, "type": "idiom", "en": "comply with ~", "ja": "~に従う", "ex": "All staff must comply with the policy."},
  {"lv": 4, "type": "idiom", "en": "contribute to ~", "ja": "~に貢献する", "ex": "She contributed to the success."},
  {"lv": 4, "type": "idiom", "en": "in the event of ~", "ja": "~の場合には", "ex": "In the event of rain, we'll stay in."},
  {"lv": 4, "type": "idiom", "en": "look into ~", "ja": "~を調査する", "ex": "We will look into the matter."},
  {"lv": 4, "type": "idiom", "en": "on the verge of ~", "ja": "~の寸前で", "ex": "The firm is on the verge of collapse."},
  {"lv": 4, "type": "idiom", "en": "rule out ~", "ja": "~を除外する", "ex": "We can't rule out that possibility."},
  {"lv": 4, "type": "idiom", "en": "run into ~", "ja": "~に偶然出会う", "ex": "I ran into an old friend."},
  {"lv": 4, "type": "idiom", "en": "set aside ~", "ja": "~を取っておく", "ex": "Set aside some time for this."},
  {"lv": 4, "type": "idiom", "en": "stand for ~", "ja": "~を表す", "ex": "What does CEO stand for?"},
  {"lv": 4, "type": "idiom", "en": "step down", "ja": "辞任する", "ex": "The president will step down in June."},
  {"lv": 4, "type": "idiom", "en": "take into account ~", "ja": "~を考慮に入れる", "ex": "Take the cost into account."},
  {"lv": 4, "type": "idiom", "en": "take advantage of ~", "ja": "~を利用する", "ex": "Take advantage of this offer."},
  {"lv": 4, "type": "idiom", "en": "in light of ~", "ja": "~を考慮して", "ex": "In light of the delay, we changed plans."},
  {"lv": 4, "type": "idiom", "en": "in the long run", "ja": "長い目で見れば", "ex": "This will save money in the long run."},
  {"lv": 4, "type": "idiom", "en": "keep track of ~", "ja": "~を把握し続ける", "ex": "I keep track of my expenses."},
  {"lv": 4, "type": "idiom", "en": "phase out ~", "ja": "~を段階的に廃止する", "ex": "They phased out the old model."},
  {"lv": 4, "type": "idiom", "en": "fill in for ~", "ja": "~の代理をする", "ex": "I'll fill in for him tomorrow."},
  {"lv": 4, "type": "idiom", "en": "hold off ~", "ja": "~を見合わせる", "ex": "Let's hold off the decision."},
  {"lv": 4, "type": "idiom", "en": "lay off ~", "ja": "~を一時解雇する", "ex": "The factory laid off 100 workers."},
  {"lv": 4, "type": "idiom", "en": "sort out ~", "ja": "~を整理する、解決する", "ex": "We need to sort out this issue."},
  {"lv": 5, "type": "word", "en": "abrupt", "ja": "突然の", "ex": "The meeting came to an abrupt end."},
  {"lv": 5, "type": "word", "en": "adjourn", "ja": "休会する", "ex": "The committee adjourned until Monday."},
  {"lv": 5, "type": "word", "en": "advocate", "ja": "擁護する", "ex": "She advocates for workers' rights."},
  {"lv": 5, "type": "word", "en": "affiliate", "ja": "提携する", "ex": "The clinic is affiliated with a university."},
  {"lv": 5, "type": "word", "en": "alleviate", "ja": "軽減する", "ex": "This medicine alleviates pain."},
  {"lv": 5, "type": "word", "en": "ambiguous", "ja": "あいまいな", "ex": "The instructions were ambiguous."},
  {"lv": 5, "type": "word", "en": "ascertain", "ja": "突き止める", "ex": "We must ascertain the facts."},
  {"lv": 5, "type": "word", "en": "attribute", "ja": "~のせいにする", "ex": "He attributed his success to luck."},
  {"lv": 5, "type": "word", "en": "avert", "ja": "未然に防ぐ", "ex": "Quick action averted a disaster."},
  {"lv": 5, "type": "word", "en": "bolster", "ja": "強化する", "ex": "The firm bolstered its security."},
  {"lv": 5, "type": "word", "en": "circumvent", "ja": "回避する、迂回する", "ex": "They tried to circumvent the rules."},
  {"lv": 5, "type": "word", "en": "coalition", "ja": "連合", "ex": "A coalition of groups opposed the plan."},
  {"lv": 5, "type": "word", "en": "collaborate", "ja": "協力する", "ex": "The two firms collaborated on the project."},
  {"lv": 5, "type": "word", "en": "concede", "ja": "認める、譲歩する", "ex": "He conceded that he was wrong."},
  {"lv": 5, "type": "word", "en": "conducive", "ja": "助けとなる", "ex": "Quiet is conducive to study."},
  {"lv": 5, "type": "word", "en": "defer", "ja": "延期する", "ex": "We deferred the decision."},
  {"lv": 5, "type": "word", "en": "deplete", "ja": "使い果たす", "ex": "The project depleted our funds."},
  {"lv": 5, "type": "word", "en": "deteriorate", "ja": "悪化する", "ex": "His health deteriorated quickly."},
  {"lv": 5, "type": "word", "en": "detrimental", "ja": "有害な", "ex": "Stress is detrimental to health."},
  {"lv": 5, "type": "word", "en": "diminish", "ja": "減少する", "ex": "Interest in the product diminished."},
  {"lv": 5, "type": "word", "en": "disseminate", "ja": "広める", "ex": "They disseminated the news online."},
  {"lv": 5, "type": "word", "en": "elaborate", "ja": "詳しく述べる", "ex": "Could you elaborate on that point?"},
  {"lv": 5, "type": "word", "en": "exacerbate", "ja": "悪化させる", "ex": "Delays exacerbated the problem."},
  {"lv": 5, "type": "word", "en": "exemplary", "ja": "模範的な", "ex": "Her conduct was exemplary."},
  {"lv": 5, "type": "word", "en": "expedite", "ja": "迅速に処理する", "ex": "We can expedite your order."},
  {"lv": 5, "type": "word", "en": "explicit", "ja": "明白な", "ex": "The rules are explicit."},
  {"lv": 5, "type": "word", "en": "fiscal", "ja": "財政の", "ex": "The fiscal year ends in March."},
  {"lv": 5, "type": "word", "en": "hamper", "ja": "妨げる", "ex": "Bad weather hampered our work."},
  {"lv": 5, "type": "word", "en": "impending", "ja": "差し迫った", "ex": "The impending storm worried everyone."},
  {"lv": 5, "type": "word", "en": "inadvertently", "ja": "うっかり", "ex": "I inadvertently deleted the file."},
  {"lv": 5, "type": "word", "en": "incur", "ja": "(損害などを)被る", "ex": "The firm incurred heavy losses."},
  {"lv": 5, "type": "word", "en": "indispensable", "ja": "不可欠な", "ex": "She is indispensable to our team."},
  {"lv": 5, "type": "word", "en": "leverage", "ja": "活用する", "ex": "We leverage technology to grow."},
  {"lv": 5, "type": "word", "en": "lucrative", "ja": "もうかる", "ex": "It was a lucrative deal."},
  {"lv": 5, "type": "word", "en": "meticulous", "ja": "細心の", "ex": "He is meticulous about details."},
  {"lv": 5, "type": "word", "en": "mitigate", "ja": "和らげる", "ex": "We must mitigate the risks."},
  {"lv": 5, "type": "word", "en": "negligible", "ja": "取るに足らない", "ex": "The difference is negligible."},
  {"lv": 5, "type": "word", "en": "notwithstanding", "ja": "~にもかかわらず", "ex": "Notwithstanding the cost, we'll go."},
  {"lv": 5, "type": "word", "en": "pertinent", "ja": "関連のある", "ex": "Please include only pertinent facts."},
  {"lv": 5, "type": "word", "en": "preliminary", "ja": "予備の", "ex": "Preliminary results are promising."},
  {"lv": 5, "type": "word", "en": "prerequisite", "ja": "前提条件", "ex": "This course is a prerequisite."},
  {"lv": 5, "type": "word", "en": "prevalent", "ja": "普及している", "ex": "The practice is prevalent in Asia."},
  {"lv": 5, "type": "word", "en": "proponent", "ja": "支持者", "ex": "He is a proponent of reform."},
  {"lv": 5, "type": "word", "en": "ratify", "ja": "批准する", "ex": "The treaty was ratified."},
  {"lv": 5, "type": "word", "en": "rectify", "ja": "是正する", "ex": "We will rectify the error."},
  {"lv": 5, "type": "word", "en": "redundant", "ja": "余剰の", "ex": "Many jobs became redundant."},
  {"lv": 5, "type": "word", "en": "reluctant", "ja": "気が進まない", "ex": "She was reluctant to speak."},
  {"lv": 5, "type": "word", "en": "scrutinize", "ja": "精査する", "ex": "Auditors scrutinized the accounts."},
  {"lv": 5, "type": "word", "en": "stringent", "ja": "厳しい", "ex": "The rules are stringent."},
  {"lv": 5, "type": "word", "en": "subsequent", "ja": "その後の", "ex": "Subsequent events proved him right."},
  {"lv": 5, "type": "word", "en": "surpass", "ja": "上回る", "ex": "Sales surpassed our targets."},
  {"lv": 5, "type": "word", "en": "unanimous", "ja": "満場一致の", "ex": "The vote was unanimous."},
  {"lv": 5, "type": "word", "en": "viable", "ja": "存続可能な", "ex": "The plan is economically viable."},
  {"lv": 5, "type": "word", "en": "withstand", "ja": "耐える", "ex": "The building can withstand earthquakes."},
  {"lv": 5, "type": "idiom", "en": "above and beyond ~", "ja": "~をはるかに超えて", "ex": "She went above and beyond her duties."},
  {"lv": 5, "type": "idiom", "en": "at the discretion of ~", "ja": "~の裁量で", "ex": "It is at the discretion of the manager."},
  {"lv": 5, "type": "idiom", "en": "be bound to ~", "ja": "きっと~する", "ex": "He is bound to succeed."},
  {"lv": 5, "type": "idiom", "en": "be contingent on ~", "ja": "~次第である", "ex": "The deal is contingent on approval."},
  {"lv": 5, "type": "idiom", "en": "be tied up", "ja": "手が離せない", "ex": "I'm tied up until noon."},
  {"lv": 5, "type": "idiom", "en": "bear in mind ~", "ja": "~を心に留める", "ex": "Bear in mind the deadline."},
  {"lv": 5, "type": "idiom", "en": "break even", "ja": "収支が合う", "ex": "We hope to break even this year."},
  {"lv": 5, "type": "idiom", "en": "by virtue of ~", "ja": "~のおかげで", "ex": "She got the job by virtue of her skills."},
  {"lv": 5, "type": "idiom", "en": "come into effect", "ja": "発効する", "ex": "The law comes into effect in May."},
  {"lv": 5, "type": "idiom", "en": "cut back on ~", "ja": "~を削減する", "ex": "We cut back on travel."},
  {"lv": 5, "type": "idiom", "en": "draw up ~", "ja": "~を作成する", "ex": "They drew up a new contract."},
  {"lv": 5, "type": "idiom", "en": "fall through", "ja": "失敗に終わる", "ex": "The deal fell through."},
  {"lv": 5, "type": "idiom", "en": "in the wake of ~", "ja": "~の結果として", "ex": "In the wake of the crisis, prices fell."},
  {"lv": 5, "type": "idiom", "en": "iron out ~", "ja": "~を解決する", "ex": "We ironed out the problems."},
  {"lv": 5, "type": "idiom", "en": "keep abreast of ~", "ja": "~に遅れずについていく", "ex": "Keep abreast of market trends."},
  {"lv": 5, "type": "idiom", "en": "on the brink of ~", "ja": "~の瀬戸際で", "ex": "The firm is on the brink of failure."},
  {"lv": 5, "type": "idiom", "en": "pave the way for ~", "ja": "~への道を開く", "ex": "This paves the way for growth."},
  {"lv": 5, "type": "idiom", "en": "play down ~", "ja": "~を軽く見せる", "ex": "He played down the risks."},
  {"lv": 5, "type": "idiom", "en": "pull off ~", "ja": "~をやってのける", "ex": "They pulled off a huge deal."},
  {"lv": 5, "type": "idiom", "en": "put forward ~", "ja": "~を提案する", "ex": "She put forward a new idea."},
  {"lv": 5, "type": "idiom", "en": "reach a consensus", "ja": "合意に達する", "ex": "We reached a consensus quickly."},
  {"lv": 5, "type": "idiom", "en": "roll out ~", "ja": "~を展開する", "ex": "They rolled out a new service."},
  {"lv": 5, "type": "idiom", "en": "stem from ~", "ja": "~に由来する", "ex": "The problem stems from poor planning."},
  {"lv": 5, "type": "idiom", "en": "steer clear of ~", "ja": "~を避ける", "ex": "Steer clear of risky deals."},
  {"lv": 5, "type": "idiom", "en": "touch base with ~", "ja": "~と連絡を取る", "ex": "I'll touch base with you next week."},
  {"lv": 5, "type": "idiom", "en": "wrap up ~", "ja": "~を終わらせる", "ex": "Let's wrap up the meeting."},
];
